### ISSUE TITLE
Buffer over-read when generating the native secret

### ISSUE THREAD

**Issue by nibarius** [nowsecure/cybertruckchallenge19#2]
https://github.com/nowsecure/cybertruckchallenge19/blob/7eb9298752b5be53d9c2e3d9d2db0affde476215/src/app/src/main/cpp/native-lib.cpp#L17-L28

Is it intended to not have any null-termination on the data array to make the challenge harder? `strlen()` reads data until it finds the first null character, which with this implementation is somewhere past the end of the data array. When I'm running this on an x86_64 emulator strlen returns 38 while the data array is 32 characters long. This also means that the last characters of the `out` array will be based on data read from past the end of the `data` and `key` arrays.

**Comment by enovella** [comment]
Hey @nibarius,

First of all, many thanks for playing it. As far as I remember, the hint was already warning you: `check the length when submitting the secret!`. This was done "kinda" on purpose and the app wasn't crashing (tested right now on emulator x86_64) although it was generating rubbish bytes with data not initialized. In any case you're right and I could have suppressed the use of `strlen` there and hardcode the length of 32 characters long. Effectively, the flag was comprised of 32 characters long.

**Comment by nibarius** [comment]
Thanks for the answer, good to know it's intended. It took me a while to figure out why my static analysis found a 33 character long key (ending with a `,`) and why strlen returned something even longer. I could of course see the real key, but I really wanted to know why this happened to make sure it wasn't my fault.

Also thanks a lot for the challenge. I've learned a lot from the third part, at first I didn't realize you could intercept individual instructions  with Frida, so I intercepted the whole init function and figured out how to pull the flag from the stack. So a lot of lessons learned from such a small and simple native function.
